FROM python:3.11-alpine
# This prevents Python from writing out pyc files
ENV PYTHONDONTWRITEBYTECODE 1
# This keeps Python from buffering stdin/stdout
ENV PYTHONUNBUFFERED 1

WORKDIR /app

USER root

COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

COPY producer.py ./producer.py

CMD ["python3", "producer.py"]