FROM ubuntu:latest

RUN apt update && apt install python3 -y && apt -y install python3-pip
RUN apt install -y protobuf-compiler

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app
USER root

COPY ../requirements.txt .
COPY .. /app

COPY ../consumer/protobuf_consumer.py /app/protobuf_consumer.py
COPY ../config.py /app/config.py
COPY ../schema.json /app/schema.json

RUN pip install -r requirements.txt --break-system-packages
CMD make consumer_pb