FROM python:3.12-slim AS builder

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    gcc \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY ../consumer/consumer_avro.py /app/consumer_avro.py
COPY ../consumer/processor.py /app/processor.py
COPY ../config.py /app/config.py
COPY ../schema.avsc /app/schema.avsc

RUN pip install pyinstaller
RUN pyinstaller --onefile consumer_avro.py

#FROM scratch

#WORKDIR /app

#COPY --from=builder /app/dist/consumer_avro /app/consumer_avro
ENTRYPOINT ["/app/dist/consumer_avro"]


