FROM python:3.12-slim AS builder
USER root
RUN apt-get update &&  \
    apt-get install -y --no-install-recommends  && \
    apt-get install -y protobuf-compiler \
    build-essential \
    gcc \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY ../producers/protobuf_producer.py /app/protobuf_producer.py
COPY ../producers/product_generator.py /app/product_generator.py
COPY ../protobuf /app/protobuf
COPY ../kafka_config.py /app/kafka_config.py

RUN protoc -I=. --python_out=. protobuf/urpd_product.proto

RUN pip install pyinstaller
RUN pyinstaller -D protobuf_producer.py --add-data "product_generator.py:." --add-data "kafka_config.py:." --add-data "protobuf/urpd_product_pb2.py:protobuf"

# Stage 2
# FROM gcr.io/distroless/python3-debian10
# FROM debian:bullseye-slim
FROM scratch

WORKDIR /app
COPY --from=builder /app/dist/protobuf_producer /app/protobuf_producer
COPY --from=builder /app/dist/protobuf_producer/_internal/kafka_config.py /app/kafka_config.py
COPY --from=builder /app/dist/protobuf_producer/_internal/product_generator.py /app/product_generator.py
COPY --from=builder /app/dist/protobuf_producer/_internal/protobuf/urpd_product_pb2.py /app/protobuf/urpd_product_pb2.py
COPY --from=builder /lib /lib
COPY --from=builder /lib64 /lib64

ENTRYPOINT ["/app/protobuf_producer/protobuf_producer"]
