FROM python:3.13
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

USER root

COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

COPY ../consumer/consumer.py /app/consumer.py
COPY ../consumer/processor.py /app/processor.py
COPY ../config.py /app/config.py
COPY ../schemas/schema.json /app/schema.json

CMD ["python", "consumer.py"]