FROM ubuntu:latest

RUN apt update && apt install python3 -y && apt -y install python3-pip
RUN apt install -y protobuf-compiler

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app
USER root

COPY ../requirements.txt .
COPY .. /app

COPY ../consumers/protobuf_consumer.py /app/protobuf_consumer.py
COPY ../consumers/processor.py /app/processor.py
COPY ../kafka_config.py /app/config.py
COPY ../schemas/schema.json /app/schema.json

RUN pip install -r requirements.txt --break-system-packages
CMD make consumer_pb