FROM python:3.12-slim AS builder
USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    gcc \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY ../producers/producer.py /app/producer.py
COPY ../producers/product_generator.py /app
COPY ../kafka_config.py /app/kafka_config.py
COPY ../schemas/schema.json /app/schema.json

WORKDIR /app
COPY --from=builder /app/dist/producer /app/producer
COPY --from=builder /app/dist/producer/_internal/kafka_config.py /app/kafka_config.py
COPY --from=builder /app/dist/producer/_internal/processor.py /app/processor.py
COPY --from=builder /app/dist/producer/_internal/schema.avsc /app/schema.json
COPY --from=builder /lib /lib

ENTRYPOINT ["/app/producer/producer"]