FROM python:3.12-slim AS builder
USER root
RUN apt-get update &&  \
    apt-get install -y --no-install-recommends  && \
    apt-get install -y protobuf-compiler \
    build-essential \
    gcc \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY ../consumers/protobuf_consumer.py /app/protobuf_consumer.py
COPY ../protobuf /app/protobuf
COPY ../consumers/processor.py /app/processor.py
COPY ../kafka_config.py /app/kafka_config.py

RUN protoc -I=. --python_out=. protobuf/urpd_product.proto

RUN pip install pyinstaller
RUN pyinstaller -D protobuf_consumer.py --add-data "processor.py:." --add-data "kafka_config.py:." --add-data "protobuf/urpd_product_pb2.py:protobuf"

#FROM scratch
FROM gcr.io/distroless/python3-debian10
WORKDIR /app
COPY --from=builder /app/dist/protobuf_consumer /app/protobuf_consumer
COPY --from=builder /app/dist/protobuf_consumer/_internal/kafka_config.py /app/kafka_config.py
COPY --from=builder /app/dist/protobuf_consumer/_internal/processor.py /app/processor.py
COPY --from=builder /app/dist/protobuf_consumer/_internal/protobuf/urpd_product_pb2.py /app/protobuf/urpd_product_pb2.py
COPY --from=builder /lib /lib

ENTRYPOINT ["/app/protobuf_consumer/protobuf_consumer"]
