FROM python:3.12-slim AS builder
USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    gcc \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY ../producers/producer.py /app/producer.py
COPY ../producers/product_generator.py /app/product_generator.py
COPY ../kafka_config.py /app/kafka_config.py
COPY ../schemas/schema.json /app/schema.json

RUN pip install pyinstaller
RUN pyinstaller -D producer.py --add-data "product_generator.py:." --add-data "kafka_config.py:." --add-data "schema.json:."

# Stage 2
# FROM gcr.io/distroless/python3-debian10
# FROM debian:bullseye-slim
FROM scratch
WORKDIR /app

COPY --from=builder /app/dist/producer /app/producer
COPY --from=builder /app/dist/producer/_internal/kafka_config.py /app/kafka_config.py
COPY --from=builder /app/dist/producer/_internal/product_generator.py /app/product_generator.py
COPY --from=builder /app/dist/producer/_internal/schema.json /app/schema.json
COPY --from=builder /lib /lib
COPY --from=builder /lib64 /lib64

ENTRYPOINT ["/app/producer/producer"]